# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
gems: [jekyll-paginate]
title: 통계 스토리
email: jkim@iastate.edu
description: > # this means to ignore newlines until "baseurl:"
  김재광 교수의 풀어쓴 통계학 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jaekwangkim.com" # the base hostname & protocol for your site
#twitter_username: TWRITTER_USERNAME
github_username: kim00020
sass:
  style: compressed
# Pagination
paginate: 5
paginate_path: "page:num"
# Build settings
markdown: kramdown

# Newsletter URL
# mailchimp: "//bitwiser.us10.list-manage.com/subscribe/post?u=98dffea21944db66c8fa221ec&amp;id=8cc0f04ed1"

# Analytics
# ga_id: UA-47902363-1
# ga_domain: bitwiser.in
# disqus: bitwiser
