#
###################################
# Site wide configuration
####################################
#
title: 통계학 노트
email: jkim@iastate.edu
description: Statistical Notes by J.K. Kim 
url: "http://jaekwangkim.com" # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Chicago
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: KIM, Jae-kwang (김재광)
  avatar: leonids-logo.jpg
  job: "Professor, Department of Statistics, ISU
Department of Mathematical Sciences, KAIST"
  bio: https://sites.google.com/view/jaekwangkim/home
  email: jkim@iastate.edu
  disqus-shortname: http-jaekwangkim-com
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: kim00020
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
